on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      if: matrix.os == 'windows-latest'
      with:
        minimum-size: 8
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install
      run: |
        go get github.com/syndtr/goleveldb/leveldb
        go get github.com/benitogf/katamari
        go get github.com/pkg/expect
    - name: lint
      run: go vet .
    - name: Test
      run: go test -v -coverprofile cover.out -count 1 -failfast -race -bench .
